spring.application.name=notification-ms
server.port = 8084
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pvcreation.mailing@gmail.com
spring.mail.password=bayvmptvbhnuwvcx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=INFO
logging.level.com.pvcreation=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{100} - %msg%n

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


#https://www.youtube.com/watch?v=kLMUS0-PznE&t=12s